//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deel4Oefening1.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Speler", Namespace="http://schemas.datacontract.org/2004/07/Deel4Oefening1.Service")]
    [System.SerializableAttribute()]
    public partial class Speler : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BondsNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Geb_DatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<char> GeslachtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HuisNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JaartoeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SpelersNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StraatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VoorlettersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BondsNr {
            get {
                return this.BondsNrField;
            }
            set {
                if ((object.ReferenceEquals(this.BondsNrField, value) != true)) {
                    this.BondsNrField = value;
                    this.RaisePropertyChanged("BondsNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Geb_Datum {
            get {
                return this.Geb_DatumField;
            }
            set {
                if ((this.Geb_DatumField.Equals(value) != true)) {
                    this.Geb_DatumField = value;
                    this.RaisePropertyChanged("Geb_Datum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<char> Geslacht {
            get {
                return this.GeslachtField;
            }
            set {
                if ((this.GeslachtField.Equals(value) != true)) {
                    this.GeslachtField = value;
                    this.RaisePropertyChanged("Geslacht");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HuisNr {
            get {
                return this.HuisNrField;
            }
            set {
                if ((object.ReferenceEquals(this.HuisNrField, value) != true)) {
                    this.HuisNrField = value;
                    this.RaisePropertyChanged("HuisNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Jaartoe {
            get {
                return this.JaartoeField;
            }
            set {
                if ((this.JaartoeField.Equals(value) != true)) {
                    this.JaartoeField = value;
                    this.RaisePropertyChanged("Jaartoe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naam {
            get {
                return this.NaamField;
            }
            set {
                if ((object.ReferenceEquals(this.NaamField, value) != true)) {
                    this.NaamField = value;
                    this.RaisePropertyChanged("Naam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Plaats {
            get {
                return this.PlaatsField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaatsField, value) != true)) {
                    this.PlaatsField = value;
                    this.RaisePropertyChanged("Plaats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Postcode {
            get {
                return this.PostcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostcodeField, value) != true)) {
                    this.PostcodeField = value;
                    this.RaisePropertyChanged("Postcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SpelersNr {
            get {
                return this.SpelersNrField;
            }
            set {
                if ((this.SpelersNrField.Equals(value) != true)) {
                    this.SpelersNrField = value;
                    this.RaisePropertyChanged("SpelersNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Straat {
            get {
                return this.StraatField;
            }
            set {
                if ((object.ReferenceEquals(this.StraatField, value) != true)) {
                    this.StraatField = value;
                    this.RaisePropertyChanged("Straat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefoon {
            get {
                return this.TelefoonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoonField, value) != true)) {
                    this.TelefoonField = value;
                    this.RaisePropertyChanged("Telefoon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Voorletters {
            get {
                return this.VoorlettersField;
            }
            set {
                if ((object.ReferenceEquals(this.VoorlettersField, value) != true)) {
                    this.VoorlettersField = value;
                    this.RaisePropertyChanged("Voorletters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSpelers", ReplyAction="http://tempuri.org/IService1/GetSpelersResponse")]
        Deel4Oefening1.ServiceReference.Speler[] GetSpelers(string naam, System.DateTime geboorteDatum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSpelers", ReplyAction="http://tempuri.org/IService1/GetSpelersResponse")]
        System.Threading.Tasks.Task<Deel4Oefening1.ServiceReference.Speler[]> GetSpelersAsync(string naam, System.DateTime geboorteDatum);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Deel4Oefening1.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Deel4Oefening1.ServiceReference.IService1>, Deel4Oefening1.ServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Deel4Oefening1.ServiceReference.Speler[] GetSpelers(string naam, System.DateTime geboorteDatum) {
            return base.Channel.GetSpelers(naam, geboorteDatum);
        }
        
        public System.Threading.Tasks.Task<Deel4Oefening1.ServiceReference.Speler[]> GetSpelersAsync(string naam, System.DateTime geboorteDatum) {
            return base.Channel.GetSpelersAsync(naam, geboorteDatum);
        }
    }
}
